import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Plus, X } from "lucide-react";
import { PageHeader, StatCard, StatusBadge } from "../components/UI";
import type { Appointment, AppointmentStatus } from "../clinicalWorkflowData";
import type { StaffRole } from "../types";

const statusLabel: Record<AppointmentStatus, string> = { pending: "待就诊", completed: "已完成", cancelled: "已取消" };

export function AppointmentManagementPage({ role, accountId, appointments, setAppointments }: { role: StaffRole; accountId: string; appointments: Appointment[]; setAppointments: React.Dispatch<React.SetStateAction<Appointment[]>> }) {
  const [selectedDate, setSelectedDate] = useState("2026-08-05");
  const [editing, setEditing] = useState<Appointment | null>(null);
  const [error, setError] = useState("");
  const rows = useMemo(() => appointments.filter((item) => item.date === selectedDate && (role !== "DOCTOR" || item.doctorId === accountId)), [appointments, selectedDate, role, accountId]);
  const counts = (status: AppointmentStatus) => rows.filter((item) => item.status === status).length;
  const canEdit = role === "REHAB_EXECUTION";

  function save() {
    if (!editing) return;
    const collision = appointments.some((item) => item.id !== editing.id && item.date === editing.date && item.time === editing.time && item.status !== "cancelled" && (item.patientId === editing.patientId || item.station === editing.station));
    if (collision) { setError("该患者或工位在所选时间已有预约，请调整时间或工位。"); return; }
    setAppointments((items) => items.some((item) => item.id === editing.id) ? items.map((item) => item.id === editing.id ? editing : item) : [...items, editing]);
    setSelectedDate(editing.date); setEditing(null); setError("");
  }

  return <section data-testid="page-VIEW-APPOINTMENTS"><PageHeader eyebrow="到诊安排 · 训练资源" title="预约管理" description="康复师维护到诊时间、运动项目和工位；医生查看本人患者安排，管理员只读。" action={canEdit ? <button className="btn-primary" onClick={() => setEditing({ id: `APT-${Date.now()}`, date: selectedDate, time: "09:00", patientId: "P-DEMO-001", patientName: "陈女士", risk: "中危", status: "pending", project: "功率车", station: "功率车01", doctorId: "doctor001", doctorName: "王医生", note: "" })}><Plus className="h-4 w-4" />新建预约</button> : <StatusBadge tone="blue">只读视图</StatusBadge>} />
    <div className="grid gap-5 lg:grid-cols-[330px_1fr]"><section className="card p-5"><h2 className="flex items-center gap-2 text-sm font-bold"><CalendarDays className="h-4 w-4 text-blue-600" />2026年8月</h2><div className="mt-5 grid grid-cols-7 gap-1 text-center text-xs"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span>{Array.from({ length: 35 }, (_, index) => { const day = index - 4; const valid = day >= 1 && day <= 31; const date = valid ? `2026-08-${String(day).padStart(2, "0")}` : ""; const total = appointments.filter((item) => item.date === date && item.status !== "cancelled").length; return <button disabled={!valid} key={index} onClick={() => valid && setSelectedDate(date)} className={`relative h-10 rounded-lg ${date === selectedDate ? "bg-blue-600 text-white" : valid ? "hover:bg-blue-50" : "text-slate-300"}`}>{valid ? day : ""}{total > 0 && <span className={`absolute bottom-1 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full ${date === selectedDate ? "bg-white" : "bg-blue-500"}`} />}</button>; })}</div></section><div><section className="card p-5"><h2 className="text-sm font-bold">{selectedDate} 预约（{rows.length}）</h2><div className="mt-4 space-y-2">{rows.map((item) => <div key={item.id} className="flex items-center gap-4 rounded-xl border border-slate-100 p-3"><span className="w-16 rounded-xl bg-blue-50 py-2 text-center text-sm font-bold text-blue-700">{item.time}</span><span className="flex-1"><b>{item.patientName}</b><span className="ml-2 text-[10px] text-slate-400">{item.patientId}</span><span className="mt-1 block text-[10px] text-slate-500">{item.risk} · {item.project} · {item.station} · {item.doctorName} · {item.note}</span></span><StatusBadge tone={item.status === "completed" ? "green" : item.status === "cancelled" ? "gray" : "blue"}>{statusLabel[item.status]}</StatusBadge>{canEdit && <div className="flex gap-2"><button className="text-xs font-bold text-blue-600" onClick={() => setEditing(item)}>编辑</button>{item.status === "pending" && <><button className="text-xs font-bold text-emerald-600" onClick={() => setAppointments((items) => items.map((row) => row.id === item.id ? { ...row, status: "completed" } : row))}>完成</button><button className="text-xs font-bold text-red-500" onClick={() => setAppointments((items) => items.map((row) => row.id === item.id ? { ...row, status: "cancelled" } : row))}>取消</button></>}</div>}</div>)}</div></section><div className="mt-4 grid grid-cols-3 gap-4"><StatCard label="待就诊" value={String(counts("pending"))} icon={<CalendarDays className="h-4 w-4" />} /><StatCard label="已完成" value={String(counts("completed"))} tone="green" icon={<CheckCircle2 className="h-4 w-4" />} /><StatCard label="已取消" value={String(counts("cancelled"))} /></div></div></div>
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-6"><article className="w-full max-w-xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-lg font-bold">{appointments.some((item) => item.id === editing.id) ? "编辑预约" : "新建预约"}</h2><button onClick={() => setEditing(null)}><X className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-2 gap-4">{[["日期", "date"], ["时间", "time"], ["患者姓名", "patientName"], ["患者编号", "patientId"], ["运动项目", "project"], ["工位", "station"], ["责任医生", "doctorName"], ["备注", "note"]].map(([label, key]) => <label key={key}><span className="field-label">{label}</span><input type={key === "date" ? "date" : key === "time" ? "time" : "text"} className="text-field" value={String(editing[key as keyof Appointment])} onChange={(event) => setEditing({ ...editing, [key]: event.target.value })} /></label>)}</div>{error && <p className="mt-3 text-xs font-bold text-red-600">{error}</p>}<div className="mt-5 flex justify-end"><button className="btn-primary" onClick={save}>保存预约</button></div></article></div>}
  </section>;
}
